# Generated by Django 3.2.3 on 2021-05-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField(blank=True)),
                ('discount_price', models.FloatField(blank=True)),
                ('units', models.IntegerField()),
                ('cover', models.ImageField(blank=True, upload_to='covers/%Y/%m/%d')),
            ],
        ),
    ]
