# Generated by Django 3.2.3 on 2021-06-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
