# Generated by Django 3.2.3 on 2021-05-14 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_category_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_parents',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='product.category'),
        ),
    ]
