# Generated by Django 3.2.3 on 2021-05-14 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_parents_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_parents',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='product.category'),
        ),
    ]
