# Generated by Django 3.2.3 on 2021-05-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.BooleanField(default=True)),
                ('currency', models.TextField(default='€', max_length=2)),
            ],
        ),
    ]
