# Generated by Django 3.2.3 on 2021-07-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_auto_20210701_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.TextField(default='0', max_length=150),
        ),
    ]
