# Generated by Django 3.2.3 on 2021-06-25 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin_panel', '0003_auto_20210514_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_info', serialize=False, to='auth.user', to_field='username')),
                ('state', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=60)),
                ('zip_address', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=20)),
                ('instruction', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
